### PR TITLE
Vs2022

### PR DESCRIPTION
**Pull request by barnuri**
# Title

### CODE REVIEW

**Comment by barnuri** [comment]
https://github.com/Elders/VSE-FormatDocumentOnSave/issues/40

fix the build of vs2020

**Comment by mynkow** [comment]
@barnuri thank you for the PR. Indeed this solution is building successfully. However it does not produce the VSIX for some reason. I am trying to fix this right now but it seems like I will have to rewrite the entire extension from scratch. 

:(

**Comment by mynkow** [comment]
@barnuri this is fantastic. I am testing this with VS2019 to see if everything is OK. While I am doing this could you please check what is the problem with this when I am trying to install the VSIX:
image

Also, could you please remove the `*.csproj.user` file as well.

Thank you so much, magician ;)

**Comment by mynkow** [comment]
So, it is working on VS2022 properly but it crashes on VS2019. I am investigating...

**Comment by barnuri** [comment]
any updates ? @mynkow

**Pull request merged**
